# Generated by Django 5.0 on 2024-04-26 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_dailyhoroscopes_monthlyhoroscopes_natalchartanalysis_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='dailyhoroscopes',
        ),
        migrations.DeleteModel(
            name='monthlyhoroscopes',
        ),
        migrations.DeleteModel(
            name='NatalChartAnalysis',
        ),
        migrations.DeleteModel(
            name='weeklyhoroscopes',
        ),
        migrations.DeleteModel(
            name='yearlyhoroscopes',
        ),
        migrations.DeleteModel(
            name='zodaic',
        ),
    ]
